version: '3.8'

services:
  nginx:
    build: ./nginx
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build: app
    command: gunicorn --workers=4 project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    environment:
        - POSTGRES_USER=my_proj
        - POSTGRES_PASSWORD=my_proj
        - POSTGRES_DB=my_proj_dev
  redis:
    image: redis:latest

volumes:
  postgres_data:
