# Generated by Django 4.2.4 on 2023-08-19 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.bookmarktype', verbose_name='Тип ссылки'),
        ),
    ]
